#!/usr/bin/env bash

# preprocess: Cleans a given board game dataset file.
#
# This script performs the following transformations:
# 1. Converts semicolon (;) separators to tab characters.
# 2. Convert the Microsoft line endings to Unix line endings.
# 3. Changes the format of floating-point numbers to use '.' instead of ',' as the decimal point.
# 4. Deletes non-ASCII characters.
# 5. Generates new unique IDs for rows with empty ID fields.
#
# Usage: preprocess <input_file>


# Argument Validation
if [ "$#" -ne 1 ]; then
    echo "Correct Input Format: $0 <input_file>" >&2
    exit 1
fi

input_file="$1"

if [ ! -f "$input_file" ] || [ ! -r "$input_file" ]; then
    echo "Error: File '$input_file' not found or not readable." >&2
    exit 1
fi

# Generating new IDs for empty ID fields, from the maximum id + 1
max_id=$(sort $input_file -nr | head -n 1 | cut -f1 -d';')

# Handle Microsoft line endings (remove \r) using sed.
sed 's/\r$//' "$input_file" | \

# Delete non-ASCII characters using tr.
tr -cd '\000-\177\n' | \

# Pipe the result to awk
gawk -v max_id="$max_id" -f preprocess.awk
